import { Injectable } from '@angular/core';
import { CategoryDef, UnitDef, Precision } from '../models/models';
const u=(id:string,name:string,symbol:string,factor:number,aliases:string[]=[]):UnitDef=>({id,name,symbol,factor,aliases:[id,name.toLowerCase(),symbol.toLowerCase(),...aliases]});
const c=(id:string,name:string,shortName:string,icon:string,description:string,group:CategoryDef['group'],units:UnitDef[]):CategoryDef=>({id,name,shortName,icon,description,group,units});
@Injectable({providedIn:'root'}) export class ConversionService {
readonly categories:CategoryDef[]=[
 c('length','Length','Length','swap-vertical-outline','Distance and length measurements','Everyday',[u('mm','Millimeter','mm',.001,['millimetre']),u('cm','Centimeter','cm',.01,['centimetre']),u('m','Meter','m',1,['meter','metre','meters','metres']),u('km','Kilometer','km',1000,['kilometre']),u('in','Inch','in',.0254,['inch','inches']),u('ft','Foot','ft',.3048,['feet']),u('yd','Yard','yd',.9144),u('mi','Mile','mi',1609.344,['miles']),u('nmi','Nautical Mile','nmi',1852),u('um','Micrometer','μm',1e-6,['micron']),u('nm','Nanometer','nm',1e-9),u('ly','Light Year','ly',9.4607304725808e15)]),
 c('weight','Weight / Mass','Weight','barbell-outline','Mass and weight measurements','Everyday',[u('mg','Milligram','mg',1e-6),u('g','Gram','g',.001),u('kg','Kilogram','kg',1,['kilo']),u('t','Metric Ton','t',1000,['tonne']),u('oz','Ounce','oz',.028349523125),u('lb','Pound','lb',.45359237,['lbs','pounds']),u('st','Stone','st',6.35029318),u('uston','US Ton','US ton',907.18474),u('impton','Imperial Ton','imp ton',1016.0469088),u('ug','Microgram','μg',1e-9)]),
 c('temperature','Temperature','Temperature','thermometer-outline','Celsius, Fahrenheit and absolute scales','Everyday',[{id:'c',name:'Celsius',symbol:'°C',aliases:['c','celsius','centigrade']},{id:'f',name:'Fahrenheit',symbol:'°F',aliases:['f','fahrenheit']},{id:'k',name:'Kelvin',symbol:'K',aliases:['k','kelvin']},{id:'r',name:'Rankine',symbol:'°R',aliases:['rankine','r']},{id:'re',name:'Réaumur',symbol:'°Ré',aliases:['reaumur','réaumur','re']}]),
 c('volume','Volume','Volume','beaker-outline','Liquid and cubic volume measurements','Everyday',[u('ml','Milliliter','mL',.001),u('l','Liter','L',1,['litre']),u('m3','Cubic Meter','m³',1000),u('cm3','Cubic Centimeter','cm³',.001),u('tsp','Teaspoon','tsp',.00492892159375),u('tbsp','Tablespoon','tbsp',.01478676478125),u('floz','Fluid Ounce','fl oz',.0295735295625),u('cup','Cup','cup',.2365882365),u('pt','Pint','pt',.473176473),u('qt','Quart','qt',.946352946),u('gal','Gallon','gal',3.785411784),u('ft3','Cubic Foot','ft³',28.316846592)]),
 c('area','Area','Area','square-outline','Surface area measurements','Everyday',[u('m2','Square Meter','m²',1),u('km2','Square Kilometer','km²',1e6),u('cm2','Square Centimeter','cm²',1e-4),u('mm2','Square Millimeter','mm²',1e-6),u('ft2','Square Foot','ft²',.09290304),u('in2','Square Inch','in²',.00064516),u('yd2','Square Yard','yd²',.83612736),u('acre','Acre','ac',4046.8564224),u('ha','Hectare','ha',10000)]),
 c('speed','Speed','Speed','speedometer-outline','Travel and motion speeds','Everyday',[u('ms','Meter/second','m/s',1),u('kmh','Kilometer/hour','km/h',1/3.6,['kph']),u('mph','Mile/hour','mph',.44704),u('fts','Foot/second','ft/s',.3048),u('knot','Knot','kn',.514444444444),u('mach','Mach','Ma',343,['mach'])]),
 c('time','Time','Time','time-outline','Durations and calendar periods','Everyday',[u('ms','Millisecond','ms',.001),u('s','Second','s',1),u('min','Minute','min',60),u('h','Hour','h',3600,['hr']),u('day','Day','day',86400),u('week','Week','wk',604800),u('month','Month (average)','mo',2629800),u('year','Year (365.25 days)','yr',31557600)]),
 c('energy','Energy','Energy','flash-outline','Energy, heat and work','Science & Engineering',[u('j','Joule','J',1),u('kj','Kilojoule','kJ',1000),u('cal','Calorie','cal',4.184),u('kcal','Kilocalorie','kcal',4184),u('wh','Watt-hour','Wh',3600),u('kwh','Kilowatt-hour','kWh',3.6e6),u('ev','Electronvolt','eV',1.602176634e-19),u('btu','BTU','BTU',1055.05585262)]),
 c('pressure','Pressure','Pressure','resize-outline','Atmospheric and mechanical pressure','Science & Engineering',[u('pa','Pascal','Pa',1),u('kpa','Kilopascal','kPa',1000),u('mpa','Megapascal','MPa',1e6),u('bar','Bar','bar',1e5),u('mbar','Millibar','mbar',100),u('psi','PSI','psi',6894.757293168),u('atm','Atmosphere','atm',101325),u('torr','Torr','Torr',133.3223684211),u('mmhg','mmHg','mmHg',133.322387415)]),
 c('power','Power','Power','flash-outline','Power and mechanical output','Science & Engineering',[u('w','Watt','W',1),u('kw','Kilowatt','kW',1000),u('mw','Megawatt','MW',1e6),u('hp','Horsepower','hp',745.699871582),u('btuh','BTU/hour','BTU/h',.293071070172)]),
 c('frequency','Frequency','Frequency','radio-outline','Cycles and rotations per second','Science & Engineering',[u('hz','Hertz','Hz',1),u('khz','Kilohertz','kHz',1e3),u('mhz','Megahertz','MHz',1e6),u('ghz','Gigahertz','GHz',1e9),u('rpm','RPM','rpm',1/60)]),
 c('data','Data Storage','Data','server-outline','Digital storage using binary multiples','More Tools',[u('b','Byte','B',1),u('kb','Kilobyte','KB',1024),u('mb','Megabyte','MB',1024**2),u('gb','Gigabyte','GB',1024**3),u('tb','Terabyte','TB',1024**4),u('bit','Bit','bit',.125)]),
 c('data-rate','Data Transfer Rate','Data Rate','wifi-outline','Network and transfer speeds','More Tools',[u('bps','bit/second','bps',1),u('kbps','Kilobit/second','Kbps',1e3),u('mbps','Megabit/second','Mbps',1e6),u('gbps','Gigabit/second','Gbps',1e9),u('MBps','Megabyte/second','MB/s',8e6)]),
 c('angle','Angle','Angle','compass-outline','Angular measurements','More Tools',[u('deg','Degree','°',1),u('rad','Radian','rad',180/Math.PI),u('grad','Gradian','gon',.9),u('turn','Turn','turn',360)]),
 c('force','Force','Force','fitness-outline','Force measurements','More Tools',[u('n','Newton','N',1),u('kn','Kilonewton','kN',1000),u('lbf','Pound-force','lbf',4.4482216152605),u('kgf','Kilogram-force','kgf',9.80665)]),
 c('torque','Torque','Torque','sync-outline','Rotational force','More Tools',[u('nm','Newton-meter','N·m',1),u('lbft','Pound-foot','lb·ft',1.3558179483314),u('lbin','Pound-inch','lb·in',.1129848290276),u('kgfm','Kilogram-force meter','kgf·m',9.80665)]),
 c('fuel','Fuel Economy','Fuel','car-outline','Vehicle fuel consumption','More Tools',[{id:'kml',name:'Kilometer/liter',symbol:'km/L',aliases:['km/l','kml']},{id:'l100',name:'Liter/100 km',symbol:'L/100km',aliases:['l/100km','l100']},{id:'mpg',name:'US MPG',symbol:'mpg',aliases:['mpg','miles per gallon']},{id:'impmpg',name:'Imperial MPG',symbol:'imp mpg',aliases:['imperial mpg']}])
];
 getCategory(id:string){return this.categories.find(x=>x.id===id)}
 convert(value:number,categoryId:string,fromId:string,toId:string):number { if(!Number.isFinite(value)) return NaN; if(fromId===toId)return value; if(categoryId==='temperature') return this.temperature(value,fromId,toId); if(categoryId==='fuel') return this.fuel(value,fromId,toId); const cat=this.getCategory(categoryId); const from=cat?.units.find(x=>x.id===fromId),to=cat?.units.find(x=>x.id===toId); if(!from?.factor||!to?.factor) throw new Error('Unknown unit'); return value*from.factor/to.factor; }
 private temperature(v:number,from:string,to:string){let c=from==='c'?v:from==='f'?(v-32)*5/9:from==='k'?v-273.15:from==='r'?(v-491.67)*5/9:v*1.25; return to==='c'?c:to==='f'?c*9/5+32:to==='k'?c+273.15:to==='r'?(c+273.15)*9/5:c*.8;}
 private fuel(v:number,from:string,to:string){if(v===0)return Infinity; const toKml=(x:number,id:string)=>id==='kml'?x:id==='l100'?100/x:id==='mpg'?x*.425143707:id==='impmpg'?x*.3540061899:x; const k=toKml(v,from); return to==='kml'?k:to==='l100'?100/k:to==='mpg'?k/.425143707:k/.3540061899;}
 format(value:number,precision:Precision):string { if(!Number.isFinite(value)) return value===Infinity?'∞':'—'; if(precision!=='auto') return value.toFixed(Number(precision)); const abs=Math.abs(value); if(abs!==0&&(abs>=1e9||abs<1e-6)) return value.toExponential(6).replace(/\.0+e/,'e'); return new Intl.NumberFormat(undefined,{maximumFractionDigits:6}).format(value); }
 findUnit(category:CategoryDef,term:string){const q=term.trim().toLowerCase().replace(/[°]/g,''); return category.units.find(unit=>unit.aliases.some(a=>a.toLowerCase()===q)||unit.symbol.toLowerCase()===q);}
}
